version: '3'

services:
  web:
    build: .
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    celery -A pbp_project worker --loglevel=info --detach &&
                    python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    networks:
      - pbp_project_network
    restart:
      "on-failure"
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=erick
      - POSTGRES_DB=users
      - PGPORT=5432
      - POSTGRES_USER=erick
    ports:
      - 5432:5432
    networks:
      - pbp_project_network
    restart:
      "on-failure"

  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
    networks:
      - pbp_project_network
volumes:
  postgres_data:

networks:
  pbp_project_network:
    driver: bridge
