# Generated by Django 4.0 on 2023-02-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fileupload", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="finger_print_signature",
            field=models.CharField(max_length=50),
        ),
    ]
